[build]
  publish = "build/"
  command = "NODE_OPTIONS='--openssl-legacy-provider' npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
